name = "maga os "
description = "the best distro ever"
base_image = "ghcr.io/ublue-os/silverblue-main"

modules = [
  "bling/gnome-vanilla",      
  "bling/kernel-mainline",    
  "bling/mesa-git",           
  "bling/flathub"             
]

[rpm]
install = [
  "steam",                    
  "zsh",                      
  "util-linux-user"          
]


[flatpak]
apps = [
  "com.github.tchx84.Flatseal",  
]

[gnome_extensions]
install = []

[post]
script = '''
sed -i 's|/bin/bash|/bin/zsh|g' /etc/default/useradd
'''
